LOAD DATA LOCAL INFILE "user.dat"
INTO TABLE User
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "item.dat"
INTO TABLE Item
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "category.dat"
INTO TABLE Category
FIELDS TERMINATED BY "<>";

LOAD DATA LOCAL INFILE "bid.dat"
INTO TABLE Bid
FIELDS TERMINATED BY "<>";
